version: "3.9"

services:
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: sport_bot_db
    ports:
      - "5432:5432"
    env_file: .env
  redis:
    image: redis
    container_name: sport_bot_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
