"""create table statistics_approaches

Revision ID: 1e109e3a0f49
Revises: fe38f4e1ecd1
Create Date: 2023-03-19 18:23:24.331858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e109e3a0f49'
down_revision = 'fe38f4e1ecd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_approaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statistics_exercise_id', sa.Integer(), nullable=True),
    sa.Column('approaches', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['statistics_exercise_id'], ['statistics_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('statistics_exercises', 'done')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics_exercises', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('statistics_approaches')
    # ### end Alembic commands ###
