"""add filed telegram id image

Revision ID: b3d2a439022e
Revises: 2805d8614fbe
Create Date: 2023-01-28 16:10:22.697482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d2a439022e'
down_revision = '2805d8614fbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('telegram_image_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'telegram_image_id')
    # ### end Alembic commands ###
