"""add field user_id in statistics_exercises

Revision ID: fe38f4e1ecd1
Revises: 9ffe0562e8b7
Create Date: 2023-02-26 15:41:58.184259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe38f4e1ecd1'
down_revision = '9ffe0562e8b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics_exercises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statistics_exercises', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistics_exercises', type_='foreignkey')
    op.drop_column('statistics_exercises', 'user_id')
    # ### end Alembic commands ###
